version: '3.5'

services:
  api:
    build:
      context: api/.
    ports:
      - "3000:3000"
    volumes:
      - "./api/:/go/src/dottie"
    env_file:
      - .env

  frontend:
    build:
      context: app/.
    ports:
      - "8000:8000"
    volumes:
      - "./app/:/app"
      - "/app/node_modules"

  db:
    image: "postgres:latest"
    container_name: "postgres-dotties"
    ports:
      - "5522:5432"
#    volumes:
#      - db-dotties:/var/lib/postgresql/data
    env_file:
      - db/.env_db

#volumes:
#  db-dotties:

