version: '3.5'

services:
  api:
    build:
      context: api/.
    ports:
      - "3000:3000"
    volumes:
      - "./api/:/go/src/dottie"
    env_file:
      - .env
    links:
        - db

  frontend:
    build:
      context: app/.
    ports:
      - "8000:8000"
    volumes:
      - "./app/:/app"
      - "/app/node_modules"

  db:
    build:
      context: db/local_db/.
    container_name: "postgres-dotties"
    ports:
      - "5432:5432"
    volumes:
      - db-dotties:/var/lib/postgresql/data
    env_file:
      - db/.env_db
      - .env
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=dotties-dev

  migration:
    build:
      context: db/local_db/migration/.
    container_name: "migration"
    depends_on:
      - db
    env_file:
      - db/.env_db
  

volumes:
  db-dotties:

